spring.application.name=chapter-6

# PostgreSQL Database Configuration
spring.datasource.jdbc-url=${SSO_USER_DATABASE_URL:jdbc:postgresql://localhost:5432/app}
spring.datasource.username=${SSO_USER_DATABASE_USERNAME:sa}
spring.datasource.password=${SSO_USER_DATABASE_PASSWORD:Admin@123!}
spring.datasource.driver-class-name=${SSO_USER_DATABASE_DRIVER:org.postgresql.Driver}

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml
spring.liquibase.enabled=true

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.com.manning.sbip.ch06=DEBUG
logging.level.org.springframework.security=DEBUG
