# Liquibase Configuration for User Database
changeLogFile=src/main/resources/db/changelog/changelog-master.yaml
driver=${SSO_USER_DATABASE_DRIVER}
url=${SSO_USER_DATABASE_URL}
username=${SSO_USER_DATABASE_USERNAME}
password=${SSO_USER_DATABASE_PASSWORD}
verbose=true
